export const data = [
    {
        title: 'Hello World animado SCG',
        image: '/images/svg-animado.png',
        url: '/helloworld',
        day: '1',
        techs: ['React JS', 'Vite JS', 'Typescript', 'CSS', 'Phosphor Icons'],
    },
    {
        title: 'Listagem dos projetos',
        image: '/images/lista-projetos.png',
        url: 'https://github.com/andrelinos/21diasdecodigo',
        day: '2',
        techs: [
            'React JS',
            'Vite JS',
            'Typescript',
            'CSS',
            'Phosphor Icons',
            'React Router DOM',
        ],
    },
    {
        title: 'Botões animados',
        image: '/images/animatedsbuttons.png',
        url: '/animatedbuttons',
        day: '3',
        techs: [
            'React JS',
            'Vite JS',
            'Typescript',
            'CSS',
            'SASS',
            'Tailwind CSS',
        ],
    },
    {
        title: 'Criando Gráficos no ReactJS',
        image: '/images/charts.png',
        url: '/charts',
        day: '4',
        techs: [
            'React JS',
            'Vite JS',
            'Typescript',
            'ApexCharts',
            'Tailwind CSS',
        ],
    },
    {
        title: 'Fazendo fetch no ReactJS',
        image: '/images/fetchdata.png',
        url: '/table',
        day: '5',
        techs: [
            'React JS',
            'Vite JS',
            'Typescript',
            'Javascript',
            'Brazil API',
        ],
    },
    {
        title: 'Componentizando tabela',
        image: '/images/component-table.png',
        url: '/table',
        day: '6',
        techs: ['React JS', 'Vite JS', 'Typescript', 'Tailwind CSS'],
    },
];
